# Generated by Django 5.0.1 on 2024-02-09 11:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='User@mail', max_length=100)),
                ('iconColor', models.CharField(default='#9327FF', max_length=30)),
                ('phone', models.CharField(default=' ', max_length=30)),
                ('name', models.CharField(default='user', max_length=100)),
                ('short', models.CharField(default='u', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(default='', max_length=30)),
                ('color', models.CharField(default='', max_length=30)),
                ('checked', models.BooleanField(default=False)),
                ('prio', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('assignments', models.ManyToManyField(through='todolist.TaskAssignments', to='todolist.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='taskassignments',
            name='todoitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todoitem'),
        ),
    ]
