# Generated by Django 5.0.1 on 2024-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='User@mail', max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='iconColor',
            field=models.CharField(default='#9327FF', max_length=30),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contacts',
            name='short',
            field=models.CharField(default='u', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default='User@mail', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='iconColor',
            field=models.CharField(default='#9327FF', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='short',
            field=models.CharField(default='u', max_length=30),
        ),
    ]
