# Generated by Django 5.0.1 on 2024-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_contacts_email_contacts_iconcolor_contacts_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('subtask', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='assignments',
            field=models.ManyToManyField(to='todolist.contacts'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
